version: '3'
services:
  apptranshome:
    container_name: apptranshome
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    working_dir: /var/www
    volumes: 
      - ./:/var/www
  webtranshome:  
    container_name: webtranshome 
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - 80:80
    depends_on: 
      - apptranshome
      - databasetranshome
  databasetranshome:
    container_name: mysqltranshome
    image: mysql:5.7.21
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
        - "33061:3306"

volumes:
  dbdata: